<?php
/**
 * src: module/Contact/view/contact/contact/contact.phtml
 */
$title = 'Contact Me';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$this->form->setAttribute('action', $this->url('contact'));
$this->form->prepare();
?>
<?php
// open
echo $this->form()->openTag($this->form);
?>

<div class="form-group">
<?php
    echo $this->formLabel($this->form->get('email'));
    echo $this->formText($this->form->get('email'));
    echo $this->formElementErrors($this->form->get('email'));
?>
</div>

<div class="form-group">
<?php
    echo $this->formLabel($this->form->get('message'));
    echo $this->formTextarea($this->form->get('message'));
    echo $this->formElementErrors($this->form->get('message'));
?>
</div>

<div class="form-group">
<?php
    echo $this->formLabel($this->form->get('captcha'));
    echo $this->formCaptcha($this->form->get('captcha'));
    echo $this->formElementErrors($this->form->get('captcha'));
?>
</div>

<?php
// csrf
echo $this->formHidden($this->form->get('csrf'));
// submit
echo $this->formSubmit($this->form->get('submit'));
// close
echo $this->form()->closeTag();
